### PR TITLE
feat: support root aliases & extensions from babel plugin & make rule fixable

### LINKED ISSUE #19: Make the rule fixable
See the api [here](https://eslint.org/docs/developer-guide/working-with-rules-deprecated#applying-fixes)

### LINKED ISSUE #45: Support default aliases & crash when no aliases provided
In projects where I'm using `module-resolver` I often skip alias definition. Module resolver by default treats each root's subdirectory as an alias which is very convenient. I can just have absolute paths to all my modules. This is my default config 

```js
module.exports = {
  plugins: [
    [
      'module-resolver',
      {
        root: ['./src'],
        alias: {}, // plugin crashes without this prop
        extensions: ['.js', '.ts', '.tsx', '.json'],
      },
    ],
  ],
};

```

However, this plugin only supports only user-defined aliases. In addition, if `alias` prop is skipped in the config, plugin crashes.

I would like to address that, but I'm not sure If I should extend existing rule `use-alias` or define a new rule like `use-default-alias`. After shallow code analysis, I think the first option would be easier to implement since I will just extend aliases paths. In the second option, I will probably have to exclude default aliases from the `use-alias` rule since it may try to fix the same error in different ways. BTW after that, I will work on making rules fixable, this is what I need in the project.

Let me know @HeroProtagonist and I will tackle that.

### LINKED ISSUE #55: Replace extensions option with `ext` field from babel plugin config
In my opinion option `extensions` is redundant and it will be more convenient for users and more compatible with `babel-plugin-module-resolver` if we would take list of extensions from babel plugin config.

The default list of extensions is defined [here](https://github.com/tleunen/babel-plugin-module-resolver/blob/77b1bc12a70d157218310b180a510084c418a16a/src/normalizeOptions.js#L13)
`const defaultExtensions = ['.js', '.jsx', '.es', '.es6', '.mjs'];`

Extensions are used to determine whether aliased file exists or not.

So TypeScript users and also React Native users (platform-specific extensions like `file.android.js`, `file.ios.js`) have to define extensions array twice. 
It would be good to remove that option and get extensions from babel config, however, this would introduce breaking change and we should bump major version of the plugin. I assume it follows semantic versioning. 
Edit: supporting array from babel config as a default value for that option seems not to be breaking.

What do you think @HeroProtagonist ?

### PR DESCRIPTION
**Pull request by jayu**
1. This PR adds support for root aliases and fixes #45 
1. It also adds support for the extensions list from babel plugin config and closes #55 
1. It also makes the rule fixable ! and closes #19 

eslint-plugin

Todo
- [x] test changes on a real-world project. For now, I was testing on the basic react-native project.
- [x] write tests for a fix function

### CODE REVIEW

**Comment by HeroProtagonist** [comment]
@jayu thanks for all the work. I will have time to test this in the next few days to get it merged. Just from looking at the code some things to note
- let's remove the log statements [here](https://github.com/HeroProtagonist/eslint-plugin-module-resolver/pull/54/files#diff-4b393786462a25291bf07d00f3b2ca47R150) and [here](https://github.com/HeroProtagonist/eslint-plugin-module-resolver/pull/54/files#diff-4b393786462a25291bf07d00f3b2ca47R115)
- keep newline at the end of [yarn.lock](https://github.com/HeroProtagonist/eslint-plugin-module-resolver/pull/54/files#diff-8ee2343978836a779dc9f8d6b794c3b2R5439) (not sure what would have caused it to change, maybe an editor setting)

I am going to add husky pre-commit hook to run prettier and that will remove some of the other formatting noise from the PR. So you would just need to rebase from master after that

Looks good so far and thanks 👍

**Comment by jayu** [comment]
I will polish the PR soon. Currently I have a break from coding :) I will apperciate if you will find some time to test it, also i will test it on one od my projects.

**Comment by jayu** [comment]
It seems like I forgot to push some changes lasy time 😅

**Comment by HeroProtagonist** [comment]
Let me know if you need help with anything 👍

**Comment by jayu** [comment]
Hi! You can test it changes work as expected. Within two weeks I will resolve conflicts and implement tests. You can also give it a try if you have spare time 😅. I would like to finally ship it soonish

**Comment by jayu** [comment]
@HeroProtagonist tests for auto fixing added 👍 I'm done. if you don't have any other suggestions we can ship this

**Comment by HeroProtagonist** [comment]
@jayu Awesome! I am merging this into a canary branch. I am going to batch this and other changes there and then merge to master and release `v1.0`. Stay tuned 👍

**Comment by jayu** [comment]
Hi @HeroProtagonist , any idea when it will be released 😃 ?

**Comment by HeroProtagonist** [comment]
Hey!

Need to do a little refactoring. I will aim to get this done by end of the week. 👍

**Comment by HeroProtagonist** [comment]
If you download 1.0.0. It is fixable now

**Pull request merged**
